import React, { useState } from 'react';
import { ScrollText, ShieldCheck, CheckCircle2 } from 'lucide-react';

export const TermsOfService: React.FC = () => {
  return (
    <div className="space-y-6 text-gray-700">
      <div>
        <h3 className="text-xl font-bold text-gray-900 mb-2">Pico POS Terms of Service</h3>
        <p className="text-sm text-gray-500">Last updated: July 6, 2026</p>
      </div>

      <p className="leading-relaxed">
        Welcome to Pico POS, a proprietary software service developed and owned by <strong>Himpower Pvt. Ltd.</strong> 
        By activating, subscribing to, or using the Pico POS application (the "Software"), you agree to be bound by the 
        following terms and conditions (the "Terms"). Please read them carefully.
      </p>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          1. Rent-to-Own Subscription & Ownership Model
        </h4>
        <p className="leading-relaxed pl-6">
          Pico POS operates on a unique <strong>Rent-to-Own</strong> software licensing model designed to offer maximum 
          value and flexibility to business operators:
        </p>
        <ul className="list-disc pl-12 space-y-2 leading-relaxed">
          <li>
            <strong>Payment Plans:</strong> Users can choose between a monthly recurring payment plan or a lump-sum, single-payment annual plan.
          </li>
          <li>
            <strong>12-Month Ownership Threshold:</strong> Once a user has paid for 12 consecutive months of subscription (or the equivalent annual upfront payment), 
            the subscription transforms into a <strong>Perpetual, Royalty-Free License</strong>.
          </li>
          <li>
            <strong>Lifetime Access:</strong> After reaching this 12-month milestone, the user gains permanent ownership of that software version. No further 
            subscription or licensing payments will be required to run the core POS. Optional cloud storage backups or advanced future upgrades may be subject 
            to separate service fees.
          </li>
          <li>
            <strong>Cancellation & Forfeiture:</strong> If you cancel your monthly subscription before completing the full 12-month cycle, any payments made 
            up to that point are non-refundable and do not count toward a partial perpetual license.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          2. Scope of Service & Hardware Compatibility
        </h4>
        <p className="leading-relaxed pl-6">
          The Software is designed to facilitate order entry, receipt generation, sales logging, and basic analytics. 
          While Himpower Pvt. Ltd. strives to support general POS hardware (including thermal receipt printers, Bluetooth scales, 
          and tablets), you acknowledge that hardware compatibility is highly dependent on device manufacturers, browser versions, 
          and Web APIs (e.g., Web Bluetooth). We do not guarantee uninterrupted interoperability with all third-party devices.
        </p>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          3. Compliance, Taxation & Local Regulations
        </h4>
        <p className="leading-relaxed pl-6">
          The Software provides customizable fields for VAT, PAN, and local sales taxes. <strong>Himpower Pvt. Ltd. is not a tax advisor 
          or legal auditor.</strong> It is your absolute and sole responsibility to ensure that the tax rates, invoice numbers, and reports 
          generated by Pico POS comply with local tax authorities, consumer protection laws, and business regulations in your jurisdiction.
        </p>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          4. Subscriptions, Fees & Refunds
        </h4>
        <p className="leading-relaxed pl-6">
          All payments are handled securely through third-party billing providers. Subscriptions are billed in advance. 
          Except as explicitly required by local consumer laws, all subscription fees are non-refundable. Monthly subscriptions 
          renew automatically unless canceled before the billing cycle date.
        </p>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          5. Disclaimer of Warranties & Limitation of Liability
        </h4>
        <p className="leading-relaxed pl-6">
          Pico POS is provided "AS IS" and "AS AVAILABLE" without any warranties of any kind, either express or implied. 
          To the maximum extent permitted by applicable law, in no event shall Himpower Pvt. Ltd. be liable for any indirect, 
          incidental, special, exemplary, or consequential damages (including, but not limited to, loss of business profits, 
          transaction data loss, hardware failure, or business interruption) arising out of the use or inability to use this Software.
        </p>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          6. Governing Law & Jurisdiction
        </h4>
        <p className="leading-relaxed pl-6">
          These Terms shall be governed by and construed in accordance with the laws of Nepal (Himpower Headquarters), 
          without regard to its conflict of law principles. Any dispute arising from these terms shall be settled exclusively in 
          the competent courts of Kathmandu, Nepal.
        </p>
      </section>
    </div>
  );
};

export const PrivacyPolicy: React.FC = () => {
  return (
    <div className="space-y-6 text-gray-700">
      <div>
        <h3 className="text-xl font-bold text-gray-900 mb-2">Pico POS Privacy Policy</h3>
        <p className="text-sm text-gray-500">Last updated: July 6, 2026</p>
      </div>

      <p className="leading-relaxed">
        At Pico POS (developed by <strong>Himpower Pvt. Ltd.</strong>), we respect your privacy and are committed to 
        protecting the operational data of your business and personal information of your operators. This Privacy Policy 
        explains how we collect, process, secure, and disclose information when you utilize our application.
      </p>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          1. Information We Collect
        </h4>
        <p className="leading-relaxed pl-6">
          Pico POS handles two main categories of information:
        </p>
        <ul className="list-disc pl-12 space-y-2 leading-relaxed">
          <li>
            <strong>Account Information:</strong> Business name, email address, physical location, tax identifiers (PAN/VAT), and payment billing details.
          </li>
          <li>
            <strong>Transactional & POS Data:</strong> Table configurations, menu items, sales records, receipt history, order statuses, and performance statistics. 
            This data is used solely to render your dashboard, generate analytics, and support your daily business operations.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          2. Offline-First & Data Storage Architecture
        </h4>
        <p className="leading-relaxed pl-6">
          Pico POS features an offline-capable, cloud-synchronized architecture. For your convenience:
          Your transactional records are cached locally on your device to guarantee uninterrupted billing during network outages. 
          When connected to the internet, these records are securely synchronized with our cloud servers to prevent data loss 
          in the event of hardware damage or loss of your local tablet/computer.
        </p>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          3. How We Use and Share Your Data
        </h4>
        <p className="leading-relaxed pl-6">
          <strong>We do not sell, rent, trade, or distribute your transactional records or sales insights to any third parties.</strong> 
          Your business metrics are strictly confidential. We only process this data to:
        </p>
        <ul className="list-disc pl-12 space-y-2 leading-relaxed">
          <li>Provide core point-of-sale functionality, cloud backups, and transaction history.</li>
          <li>Power optional AI business insights (e.g., sales forecasting or inventory suggestions via LLM integration).</li>
          <li>Deliver payment processing settlements through licensed financial gateways (eSewa, credit terminals).</li>
          <li>Comply with valid court orders or legal auditing processes in accordance with Nepalese and international compliance laws.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          4. Security of Business Records
        </h4>
        <p className="leading-relaxed pl-6">
          We implement rigorous security measures, including HTTPS encryption for all in-transit data and server-side encryption 
          at rest, to protect your sales logs and customer info. However, because local storage is kept in your browser/device memory, 
          you are responsible for restricting physical and digital access to your local POS terminals.
        </p>
      </section>

      <section className="space-y-3">
        <h4 className="text-base font-bold text-gray-900 flex items-center gap-2">
          <CheckCircle2 size={18} className="text-indigo-600" />
          5. Contact Information
        </h4>
        <p className="leading-relaxed pl-6">
          If you have any questions or concerns regarding this Privacy Policy or your data, please contact:
          <br />
          <strong>Himpower Pvt. Ltd.</strong>
          <br />
          Email: <span className="text-indigo-600 font-mono">himpower2025@gmail.com</span>
          <br />
          Address: Kathmandu, Nepal
        </p>
      </section>
    </div>
  );
};

export const LegalDocsView: React.FC = () => {
  const [activeSubTab, setActiveSubTab] = useState<'tos' | 'privacy'>('tos');

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden animate-in fade-in slide-in-from-bottom-2 duration-300">
      <div className="border-b border-gray-100 bg-gray-50/50 p-4 flex gap-3">
        <button
          onClick={() => setActiveSubTab('tos')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-xl font-bold text-sm transition ${
            activeSubTab === 'tos'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-100'
              : 'text-gray-600 hover:bg-gray-100'
          }`}
        >
          <ScrollText size={16} />
          Terms of Service
        </button>
        <button
          onClick={() => setActiveSubTab('privacy')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-xl font-bold text-sm transition ${
            activeSubTab === 'privacy'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-100'
              : 'text-gray-600 hover:bg-gray-100'
          }`}
        >
          <ShieldCheck size={16} />
          Privacy Policy
        </button>
      </div>

      <div className="p-6 md:p-8 max-h-[600px] overflow-y-auto bg-white">
        {activeSubTab === 'tos' ? <TermsOfService /> : <PrivacyPolicy />}
      </div>
    </div>
  );
};
